const wordsList = [
  "lorem", "baguette", "rendez-vous", "fromage", "raclette", "bienvenue", "pain",
  "ipsum", "accordeon", "Paris", "Eiffel", "St Emilion", "Bordeaux",
  "beret", "alain", "révolution", "minitel", "Champs-Elysées",
  "Arc de Triomphe", "Seine", "camembert", "pamplemousse", "bof", "hein", "quincallerie",
  "formidable", "Menilmontant", "rabibocher", "aspirateur", "vachement", "trottoir",
  "papillon", "truc", "trompette", "rouflaquettes", "libellule", "grenouille", "dégeulasse",
  "en fait", "reblochon", "encore", "flâner", "inoubliable", "anges", "baleine", "bisou",
  "brume", "câlin", "chaussettes", "avoir", "chouchou", "doux", "lent", "étoiles",
  "loufoque", "grelotter", "loufoque", "soleil", "pleuvoir", "noix de coco", "éphémère",
  "dépaysant","sirène","singulier", "chatoyer", "mon chéri", "coquillage", "épanoui",
  "grèves", "hirondelle", "luciole", "myrtille", "plaisir", "le", "la", "elle", "lui", "ils",
  "chatons", "vous", "nous", "chiots", "toilettes", "ressemblant", "Montmartre",
  "pourquoi", "saperlipopette", "perlimpinpin", "salut", "bonjour", "pote", "bourguignon",
  "dessiner", "voler", "courir", "anticonstitutionnel", "rêver", "penser", "une", "exprimer",
  "enfants", "coucou", "millésime", "fleur", "cueillir", "divisons", "tatillon",
  "encombré", "peripherique", "sommet", "attachant", "conclure", "annoncer",
  "naissance", "projets", "superposés", "chapeau", "tresses", "sentiments",
  "attendre", "pourparlers", "embourbé", "au revoir", "îles", "perdues", "perdrix",
  "valise", "moussant", "bain", "cacatoès", "pédiluve", "astérisque", "physique",
  "chimie", "foule", "embelli", "pédoncules", "interstice", "joallerie", "faubourg",
  "antichambre", "fête", "allongé", "instance", "intuitive", "sens", "dessus", "dessus", "de",
  "et", "bibelots", "navire", "chavirer", "coussins", "cadrées", "jolies", "liberté",
  "egalité", "fraternité", "pouvoir", "veux", "grandir", "sac à dos", "développer",
  "lumière", "publique", "carnet", "notes", "nuit", "jour", "joues", "synonymes",
  "présence", "privées", "parole", "arc", "romanesque", "plié", "genoux", "caillou",
  "ombre", "moquette", "simple", "bagues", "traverssin", "étourdie", "ouvert", "perspective",
  "fauteuil", "vagues", "ciel", "coucher"
];

module.exports = wordsList;